-- Generated by scripts/generate_migration.py — do not edit by hand.
BEGIN;

CREATE TABLE agents (
	id VARCHAR(64) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	key_id VARCHAR(120) NOT NULL, 
	public_jwk JSON NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE authorizations (
	id VARCHAR(64) NOT NULL, 
	watch_id VARCHAR(64) NOT NULL, 
	watch_version INTEGER NOT NULL, 
	profile VARCHAR(16) NOT NULL, 
	profile_version VARCHAR(40) NOT NULL, 
	artifact_reference VARCHAR(64) NOT NULL, 
	agent_key_id VARCHAR(120) NOT NULL, 
	consent_reference VARCHAR(64) NOT NULL, 
	status VARCHAR(24) NOT NULL, 
	presentation_state VARCHAR(24) NOT NULL, 
	pending_attempt_id VARCHAR(64), 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	summary JSON NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_authorizations_watch_id ON authorizations (watch_id);

CREATE TABLE demo_faults (
	id VARCHAR(64) NOT NULL, 
	target VARCHAR(64) NOT NULL, 
	fault VARCHAR(64) NOT NULL, 
	remaining INTEGER NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE destinations (
	id VARCHAR(64) NOT NULL, 
	user_id VARCHAR(64) NOT NULL, 
	label VARCHAR(200) NOT NULL, 
	address JSON NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_destinations_user_id ON destinations (user_id);

CREATE TABLE evaluation_runs (
	id VARCHAR(64) NOT NULL, 
	watch_id VARCHAR(64) NOT NULL, 
	watch_version INTEGER NOT NULL, 
	lease_token VARCHAR(64) NOT NULL, 
	worker_id VARCHAR(120) NOT NULL, 
	started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	finished_at TIMESTAMP WITHOUT TIME ZONE, 
	selected_offer_id VARCHAR(64), 
	outcome VARCHAR(40), 
	details JSON, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_evaluation_runs_watch_id ON evaluation_runs (watch_id);

CREATE TABLE idempotency_keys (
	id SERIAL NOT NULL, 
	key VARCHAR(120) NOT NULL, 
	user_id VARCHAR(64) NOT NULL, 
	route VARCHAR(120) NOT NULL, 
	request_digest VARCHAR(64) NOT NULL, 
	response_status INTEGER NOT NULL, 
	response_body JSON NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_idempotency_scope UNIQUE (key, user_id, route)
);

CREATE TABLE merchant_health (
	merchant_id VARCHAR(64) NOT NULL, 
	consecutive_errors INTEGER NOT NULL, 
	backoff_until TIMESTAMP WITHOUT TIME ZONE, 
	last_call_at TIMESTAMP WITHOUT TIME ZONE, 
	last_error TEXT, 
	PRIMARY KEY (merchant_id)
);

CREATE TABLE metrics (
	name VARCHAR(80) NOT NULL, 
	value INTEGER NOT NULL, 
	PRIMARY KEY (name)
);

CREATE TABLE notifications (
	id VARCHAR(64) NOT NULL, 
	watch_id VARCHAR(64) NOT NULL, 
	user_id VARCHAR(64) NOT NULL, 
	dedupe_key VARCHAR(120) NOT NULL, 
	channel VARCHAR(40) NOT NULL, 
	subject VARCHAR(200) NOT NULL, 
	body TEXT NOT NULL, 
	state VARCHAR(24) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	delivered_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (dedupe_key)
);
CREATE INDEX ix_notifications_watch_id ON notifications (watch_id);

CREATE TABLE offer_observations (
	id VARCHAR(64) NOT NULL, 
	watch_id VARCHAR(64) NOT NULL, 
	evaluation_run_id VARCHAR(64), 
	merchant_id VARCHAR(64) NOT NULL, 
	native_offer_id VARCHAR(120), 
	sku VARCHAR(120), 
	variant JSON, 
	quantity_available INTEGER, 
	price_components JSON NOT NULL, 
	total_minor INTEGER, 
	currency VARCHAR(3), 
	observed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	valid_until TIMESTAMP WITHOUT TIME ZONE, 
	delivery_estimate VARCHAR(120), 
	source_reference VARCHAR(200) NOT NULL, 
	eligibility VARCHAR(32) NOT NULL, 
	reasons JSON NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_offer_observations_watch_id ON offer_observations (watch_id);
CREATE INDEX ix_offer_observations_evaluation_run_id ON offer_observations (evaluation_run_id);

CREATE TABLE outbound_events (
	id VARCHAR(64) NOT NULL, 
	attempt_id VARCHAR(64) NOT NULL, 
	kind VARCHAR(40) NOT NULL, 
	idempotency_key VARCHAR(64) NOT NULL, 
	target VARCHAR(200) NOT NULL, 
	payload_digest VARCHAR(64) NOT NULL, 
	state VARCHAR(24) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	sent_at TIMESTAMP WITHOUT TIME ZONE, 
	acknowledged_at TIMESTAMP WITHOUT TIME ZONE, 
	response_digest VARCHAR(64), 
	PRIMARY KEY (id)
);
CREATE INDEX ix_outbound_events_attempt_id ON outbound_events (attempt_id);

CREATE TABLE protocol_artifacts (
	id VARCHAR(64) NOT NULL, 
	kind VARCHAR(64) NOT NULL, 
	watch_id VARCHAR(64), 
	authorization_id VARCHAR(64), 
	attempt_id VARCHAR(64), 
	digest VARCHAR(64) NOT NULL, 
	ciphertext TEXT NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_protocol_artifacts_attempt_id ON protocol_artifacts (attempt_id);
CREATE INDEX ix_protocol_artifacts_watch_id ON protocol_artifacts (watch_id);

CREATE TABLE purchase_attempts (
	id VARCHAR(64) NOT NULL, 
	watch_id VARCHAR(64) NOT NULL, 
	watch_version INTEGER NOT NULL, 
	authorization_id VARCHAR(64) NOT NULL, 
	evaluation_run_id VARCHAR(64), 
	merchant_id VARCHAR(64) NOT NULL, 
	checkout_id VARCHAR(120) NOT NULL, 
	checkout_digest VARCHAR(64) NOT NULL, 
	final_total_minor INTEGER NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	idempotency_key VARCHAR(64) NOT NULL, 
	claim_state VARCHAR(32) NOT NULL, 
	order_state VARCHAR(32) NOT NULL, 
	payment_state VARCHAR(32) NOT NULL, 
	external_references JSON NOT NULL, 
	claimed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	submitted_at TIMESTAMP WITHOUT TIME ZONE, 
	resolved_at TIMESTAMP WITHOUT TIME ZONE, 
	last_error TEXT, 
	PRIMARY KEY (id), 
	UNIQUE (idempotency_key)
);
CREATE INDEX ix_purchase_attempts_claim_state ON purchase_attempts (claim_state);
CREATE UNIQUE INDEX uq_purchase_attempts_active_claim ON purchase_attempts (watch_id) WHERE claim_state IN ('claimed','submitting','reconciliation_required','purchased');
CREATE INDEX ix_purchase_attempts_watch_id ON purchase_attempts (watch_id);

CREATE TABLE reconciliation_cases (
	id VARCHAR(64) NOT NULL, 
	attempt_id VARCHAR(64) NOT NULL, 
	watch_id VARCHAR(64) NOT NULL, 
	state VARCHAR(24) NOT NULL, 
	summary TEXT NOT NULL, 
	evidence JSON NOT NULL, 
	checks INTEGER NOT NULL, 
	opened_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	resolved_at TIMESTAMP WITHOUT TIME ZONE, 
	resolution VARCHAR(40), 
	PRIMARY KEY (id)
);
CREATE INDEX ix_reconciliation_cases_attempt_id ON reconciliation_cases (attempt_id);
CREATE INDEX ix_reconciliation_cases_watch_id ON reconciliation_cases (watch_id);

CREATE TABLE users (
	id VARCHAR(64) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	token_sha256 VARCHAR(64) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (token_sha256)
);

CREATE TABLE watch_events (
	id SERIAL NOT NULL, 
	watch_id VARCHAR(64) NOT NULL, 
	at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	type VARCHAR(64) NOT NULL, 
	actor VARCHAR(120) NOT NULL, 
	watch_version INTEGER, 
	details JSON NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_watch_events_watch_id ON watch_events (watch_id);

CREATE TABLE watches (
	id VARCHAR(64) NOT NULL, 
	user_id VARCHAR(64) NOT NULL, 
	agent_id VARCHAR(64) NOT NULL, 
	version INTEGER NOT NULL, 
	status VARCHAR(40) NOT NULL, 
	original_request TEXT, 
	product_constraints JSON NOT NULL, 
	merchant_sku_mapping JSON NOT NULL, 
	price_operator VARCHAR(8) NOT NULL, 
	threshold_minor INTEGER NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	quantity INTEGER NOT NULL, 
	destination_id VARCHAR(64), 
	allowed_merchants JSON NOT NULL, 
	max_purchases INTEGER NOT NULL, 
	purchases_completed INTEGER NOT NULL, 
	authorization_profile VARCHAR(16) NOT NULL, 
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	timezone VARCHAR(64) NOT NULL, 
	poll_interval_seconds INTEGER NOT NULL, 
	schedule_version INTEGER NOT NULL, 
	next_check_at TIMESTAMP WITHOUT TIME ZONE, 
	lease_token VARCHAR(64), 
	lease_owner VARCHAR(120), 
	lease_expires_at TIMESTAMP WITHOUT TIME ZONE, 
	consecutive_errors INTEGER NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	cancelled_at TIMESTAMP WITHOUT TIME ZONE, 
	cancel_requested BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);
CREATE INDEX ix_watches_user_id ON watches (user_id);
CREATE INDEX ix_watches_status ON watches (status);
CREATE INDEX ix_watches_next_check_at ON watches (next_check_at);

COMMIT;
