"""Emit the PostgreSQL DDL for the current schema into migrations/001_initial.sql.

The application also calls ``metadata.create_all`` for SQLite development
databases; PostgreSQL deployments apply this file (or a future migration tool).
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages"))

from sqlalchemy.dialects import postgresql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from persistence.schema import metadata  # noqa: E402


def main() -> None:
    dialect = postgresql.dialect()
    out = ["-- Generated by scripts/generate_migration.py — do not edit by hand.", "BEGIN;", ""]
    for table in metadata.sorted_tables:
        out.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";")
        for idx in table.indexes:
            out.append(str(CreateIndex(idx).compile(dialect=dialect)).strip() + ";")
        out.append("")
    out.append("COMMIT;")
    target = ROOT / "migrations" / "001_initial.sql"
    target.parent.mkdir(exist_ok=True)
    target.write_text("\n".join(out) + "\n")
    print("wrote", target)


if __name__ == "__main__":
    main()
